export const plottyToAdamWcsColormap = {
    viridis: 'MPL_viridis',
    inferno: 'MPL_gnuplot',
    turbo: 'MPL_rainbow',
    rainbow: 'rainbow',
    jet: 'MPL_jet',
    hsv: 'MPL_hsv',
    hot: 'MPL_hot',
    cool: 'MPL_cool',
    spring: 'MPL_spring',
    summer: 'MPL_summer',
    autumn: 'MPL_autumn',
    winter: 'MPL_winter',
    bone: 'MPL_bone',
    copper: 'MPL_copper',
    greys: 'MPL_gist_gray',
    greens: 'MPL_summer',
    bluered: 'BlueRed',
    rdbu: 'MPL_RdBu',
    portland: 'BlueYellowRed',
    earth: 'MPL_gist_earth',
    electric: 'cmocean_thermal',
    coolwarm: 'MPL_coolwarm'
};
